version: 2

jobs:
  fetch:
    docker: &docker
      - image: circleci/node:14.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Node version
          command: node -v
      - run:
          name: Fetch deps
          command: yarn --frozen-lockfile
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/three-vrm/node_modules
            - packages/three-vrm-core/node_modules
            - packages/three-vrm-materials-mtoon/node_modules
            - packages/three-vrm-springbone/node_modules
            - packages/types-vrm-0.0/node_modules
            - packages/types-vrmc-materials-mtoon-1.0/node_modules
            - packages/types-vrmc-materials-hdr-emissive-multiplier-1.0/node_modules
            - packages/types-vrmc-node-constraint-1.0/node_modules
            - packages/types-vrmc-springbone-1.0/node_modules
            - packages/types-vrmc-vrm-1.0/node_modules

  build:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Fetch deps
          command: yarn --frozen-lockfile
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: '.'
          paths:
            - node_modules
            - packages/three-vrm/lib
            - packages/three-vrm/types
            - packages/three-vrm-core/lib
            - packages/three-vrm-core/types
            - packages/three-vrm-materials-mtoon/lib
            - packages/three-vrm-materials-mtoon/types
            - packages/three-vrm-springbone/lib
            - packages/three-vrm-springbone/types
            - packages/types-vrm-0.0/types
            - packages/types-vrmc-materials-mtoon-1.0/types
            - packages/types-vrmc-materials-hdr-emissive-multiplier-1.0/types
            - packages/types-vrmc-node-constraint-1.0/types
            - packages/types-vrmc-springbone-1.0/types
            - packages/types-vrmc-vrm-1.0/types

  test:
    docker: *docker
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Fetch deps
          command: yarn --frozen-lockfile
      - run:
          name: Test
          command: yarn test

  lint:
    docker: *docker
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Fetch deps
          command: yarn --frozen-lockfile
      - run:
          name: Lint
          command: yarn lint

  docs:
    docker: *docker
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Fetch deps
          command: yarn --frozen-lockfile
      - run:
          name: Docs
          command: yarn docs

workflows:
  version: 2
  inspection:
    jobs:
      - fetch
      - build:
          requires:
            - fetch
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - docs:
          requires:
            - build
